

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "EF\App.config"
//     Connection String Name: "BDConexao"
//     Connection String:      "Server=den1.mssql7.gear.host;user=webclinic;password=**zapped**;;Connect Timeout=50;Database=webclinic"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Enterprise Edition: Core-based Licensing (64-bit)
// Database Engine Edition: Enterprise

using System;
using System.Collections.Generic;
}

